################################################
####### Create output directories ####
################################################
dirs:
	mkdir -p ../out/
	mkdir -p ../plots/
	mkdir -p ../skymaps/
